name: mini_project_01_03
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/1.png
    - assets/img/2.png
    - assets/img/3.png
    - assets/img/4.png
    - assets/img/5.png
    - assets/img/6.png
